// AUTO-GENERATED by `nanoka generate`. DO NOT EDIT BY HAND.
// To regenerate: `npx nanoka generate`
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const events = sqliteTable('events', {
  id: text('id').primaryKey().notNull(),
  organizerDiscordId: text('organizerDiscordId').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  defaultDurationMinutes: integer('defaultDurationMinutes').notNull(),
  status: text('status').notNull().default("open"),
  deadline: integer('deadline', { mode: 'timestamp_ms' }),
  timezone: text('timezone').notNull().default("UTC"),
  discordChannelId: text('discordChannelId'),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const candidates = sqliteTable('candidates', {
  id: text('id').primaryKey().notNull(),
  eventId: text('eventId').notNull(),
  startAt: integer('startAt', { mode: 'timestamp_ms' }).notNull(),
  endAt: integer('endAt', { mode: 'timestamp_ms' }).notNull(),
})

export const participants = sqliteTable('participants', {
  id: text('id').primaryKey().notNull(),
  eventId: text('eventId').notNull(),
  kind: text('kind').notNull(),
  discordUserId: text('discordUserId'),
  displayName: text('displayName').notNull(),
  guestToken: text('guestToken'),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const votes = sqliteTable('votes', {
  id: text('id').primaryKey().notNull(),
  candidateId: text('candidateId').notNull(),
  participantId: text('participantId').notNull(),
  choice: text('choice').notNull(),
  comment: text('comment'),
  updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).notNull(),
})

export const decisions = sqliteTable('decisions', {
  id: text('id').primaryKey().notNull(),
  eventId: text('eventId').notNull(),
  candidateId: text('candidateId').notNull(),
  decidedAt: integer('decidedAt', { mode: 'timestamp_ms' }).notNull(),
  icsUid: text('icsUid').notNull(),
  icsSequence: integer('icsSequence').notNull().default(0),
  discordMessageId: text('discordMessageId'),
})

export const calendar_subscriptions = sqliteTable('calendar_subscriptions', {
  id: text('id').primaryKey().notNull(),
  ownerDiscordId: text('ownerDiscordId').notNull(),
  token: text('token').notNull(),
  scope: text('scope').notNull().default("user-all"),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
  lastAccessedAt: integer('lastAccessedAt', { mode: 'timestamp_ms' }),
})

export const audit_logs = sqliteTable('audit_logs', {
  id: text('id').primaryKey().notNull(),
  actorDiscordId: text('actorDiscordId'),
  action: text('action').notNull(),
  payload: text('payload', { mode: 'json' }).$type<unknown>().notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})
