// AUTO-GENERATED by `nanoka generate`. DO NOT EDIT BY HAND.
// To regenerate: `npx nanoka generate`
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const events = sqliteTable('events', {
  id: text('id').primaryKey().notNull(),
  organizerDiscordId: text('organizerDiscordId').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  defaultDurationMinutes: integer('defaultDurationMinutes').notNull(),
  status: text('status').notNull().default("open"),
  deadline: integer('deadline', { mode: 'timestamp_ms' }),
  timezone: text('timezone').notNull().default("UTC"),
  discordChannelId: text('discordChannelId'),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const candidates = sqliteTable('candidates', {
  id: text('id').primaryKey().notNull(),
  eventId: text('eventId').notNull(),
  startAt: integer('startAt', { mode: 'timestamp_ms' }).notNull(),
  endAt: integer('endAt', { mode: 'timestamp_ms' }).notNull(),
})

export const participants = sqliteTable('participants', {
  id: text('id').primaryKey().notNull(),
  eventId: text('eventId').notNull(),
  kind: text('kind').notNull(),
  discordUserId: text('discordUserId'),
  displayName: text('displayName').notNull(),
  guestTokenHash: text('guestTokenHash'),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const votes = sqliteTable('votes', {
  id: text('id').primaryKey().notNull(),
  candidateId: text('candidateId').notNull(),
  participantId: text('participantId').notNull(),
  choice: text('choice').notNull(),
  comment: text('comment'),
  updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).notNull(),
})

export const decisions = sqliteTable('decisions', {
  id: text('id').primaryKey().notNull(),
  eventId: text('eventId').notNull(),
  candidateId: text('candidateId').notNull(),
  decidedAt: integer('decidedAt', { mode: 'timestamp_ms' }).notNull(),
  icsUid: text('icsUid').notNull(),
  icsSequence: integer('icsSequence').notNull().default(0),
  discordMessageId: text('discordMessageId'),
  cancelledAt: integer('cancelledAt', { mode: 'timestamp_ms' }),
})

export const calendar_subscriptions = sqliteTable('calendar_subscriptions', {
  id: text('id').primaryKey().notNull(),
  ownerDiscordId: text('ownerDiscordId').notNull(),
  tokenHash: text('tokenHash').notNull(),
  scope: text('scope').notNull().default("user-all"),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
  lastAccessedAt: integer('lastAccessedAt', { mode: 'timestamp_ms' }),
})

export const audit_logs = sqliteTable('audit_logs', {
  id: text('id').primaryKey().notNull(),
  actorDiscordId: text('actorDiscordId'),
  action: text('action').notNull(),
  payload: text('payload', { mode: 'json' }).$type<unknown>().notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const users = sqliteTable('users', {
  id: text('id').primaryKey().notNull(),
  discordUserId: text('discordUserId').notNull(),
  username: text('username').notNull(),
  globalName: text('globalName'),
  avatar: text('avatar'),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).notNull(),
})

export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey().notNull(),
  userId: text('userId').notNull(),
  tokenHash: text('tokenHash').notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
  lastUsedAt: integer('lastUsedAt', { mode: 'timestamp_ms' }).notNull(),
  expiresAt: integer('expiresAt', { mode: 'timestamp_ms' }).notNull(),
  kind: text('kind').notNull().default("web"),
})

export const cli_auth_requests = sqliteTable('cli_auth_requests', {
  id: text('id').primaryKey().notNull(),
  deviceCodeHash: text('deviceCodeHash').notNull(),
  userCode: text('userCode').notNull(),
  status: text('status').notNull().default("pending"),
  userId: text('userId'),
  clientName: text('clientName'),
  hostname: text('hostname'),
  pollIntervalSec: integer('pollIntervalSec').notNull().default(5),
  lastPolledAt: integer('lastPolledAt', { mode: 'timestamp_ms' }),
  expiresAt: integer('expiresAt', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const feedback = sqliteTable('feedback', {
  id: text('id').primaryKey().notNull(),
  message: text('message').notNull(),
  category: text('category'),
  pageUrl: text('pageUrl'),
  eventId: text('eventId'),
  userAgent: text('userAgent'),
  submitter: text('submitter'),
  ipHash: text('ipHash'),
  status: text('status').notNull().default("new"),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})
